CREATE USER ${DBZ_USER} PASSOWRD ${DBZ_PASSWORD};

CREATE ROLE ${DBZ_ROLE} LOGIN;

GRANT rds_replication TO ${DBZ_ROLE};

GRANT SELECT ON ALL TABLES IN SCHEMA public to ${DBZ_ROLE};

GRANT CREATE ON DATABASE ${DB_NAME} TO ${DBZ_ROLE};

GRANT ${DBZ_ROLE} TO ${DBZ_USER};
